apiVersion: v1
kind: Service
metadata:
  name: speakease-backend-service
spec:
  type: NodePort
  selector:
    app: speakease-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000