apiVersion: v1
kind: Service
metadata:
  name: speakease-frontend-service
spec:
  type: NodePort
  selector:
    app: speakease-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80