apiVersion: apps/v1
kind: Deployment
metadata:
  name: speakease-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speakease-frontend
  template:
    metadata:
      labels:
        app: speakease-frontend
    spec:
      containers:
        - name: frontend
          image: lavanyaboya/speakease-frontend:latest
          ports:
            - containerPort: 80